"""add language to books_editions

Revision ID: 17d062ffd73f
Revises: f67d12b7990d
Create Date: 2025-11-29 21:48:52.214101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d062ffd73f'
down_revision: Union[str, Sequence[str], None] = 'f67d12b7990d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_editions', sa.Column('language', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_editions', 'language')
    # ### end Alembic commands ###
