"""create users_top_characters

Revision ID: 22a7d740fe08
Revises: bd8b55d6e45d
Create Date: 2025-11-29 23:49:10.208795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a7d740fe08'
down_revision: Union[str, Sequence[str], None] = 'bd8b55d6e45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_top_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_1', sa.String(length=255), nullable=True),
    sa.Column('top_2', sa.String(length=255), nullable=True),
    sa.Column('top_3', sa.String(length=255), nullable=True),
    sa.Column('top_4', sa.String(length=255), nullable=True),
    sa.Column('top_5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_top_characters_id'), 'users_top_characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_top_characters_id'), table_name='users_top_characters')
    op.drop_table('users_top_characters')
    # ### end Alembic commands ###
