"""add relations with users_personal_data

Revision ID: 2fd3813264e1
Revises: 908f851b98ac
Create Date: 2025-11-30 20:38:29.599006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd3813264e1'
down_revision: Union[str, Sequence[str], None] = '908f851b98ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_challenge_book_of_year', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenge_book_of_year', 'users_personal_data', ['user_id'], ['id'])
    op.add_column('users_challenge_books_alphabet', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenge_books_alphabet', 'users_personal_data', ['user_id'], ['id'])
    op.add_column('users_challenges', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenges', 'users_personal_data', ['user_id'], ['id'])
    op.add_column('users_statistics', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_statistics', 'users_personal_data', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_statistics', type_='foreignkey')
    op.drop_column('users_statistics', 'user_id')
    op.drop_constraint(None, 'users_challenges', type_='foreignkey')
    op.drop_column('users_challenges', 'user_id')
    op.drop_constraint(None, 'users_challenge_books_alphabet', type_='foreignkey')
    op.drop_column('users_challenge_books_alphabet', 'user_id')
    op.drop_constraint(None, 'users_challenge_book_of_year', type_='foreignkey')
    op.drop_column('users_challenge_book_of_year', 'user_id')
    # ### end Alembic commands ###
