"""add users_book_review and related tables

Revision ID: 33202f8c22ce
Revises: 2fd3813264e1
Create Date: 2025-11-30 22:43:41.622983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33202f8c22ce'
down_revision: Union[str, Sequence[str], None] = '2fd3813264e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_books_categories_id'), 'books_categories', ['id'], unique=False)
    op.create_table('users_book_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_editions.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['books_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_personal_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_book_review_id'), 'users_book_review', ['id'], unique=False)
    op.create_table('users_book_review_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['users_book_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_book_review_genres_id'), 'users_book_review_genres', ['id'], unique=False)
    op.add_column('users_book_notes', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_book_notes', 'users_book_review', ['review_id'], ['id'])
    op.add_column('users_book_quotes', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_book_quotes', 'users_book_review', ['review_id'], ['id'])
    op.add_column('users_book_rating', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users_book_rating', ['review_id'])
    op.create_foreign_key(None, 'users_book_rating', 'users_book_review', ['review_id'], ['id'])
    op.add_column('users_challenge_book_of_year', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenge_book_of_year', 'users_book_review', ['review_id'], ['id'])
    op.add_column('users_challenge_books_alphabet', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenge_books_alphabet', 'users_book_review', ['review_id'], ['id'])
    op.add_column('users_reading_records', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_reading_records', 'users_book_review', ['review_id'], ['id'])
    op.add_column('users_top_characters', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users_top_characters', ['review_id'])
    op.create_foreign_key(None, 'users_top_characters', 'users_book_review', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_top_characters', type_='foreignkey')
    op.drop_constraint(None, 'users_top_characters', type_='unique')
    op.drop_column('users_top_characters', 'review_id')
    op.drop_constraint(None, 'users_reading_records', type_='foreignkey')
    op.drop_column('users_reading_records', 'review_id')
    op.drop_constraint(None, 'users_challenge_books_alphabet', type_='foreignkey')
    op.drop_column('users_challenge_books_alphabet', 'review_id')
    op.drop_constraint(None, 'users_challenge_book_of_year', type_='foreignkey')
    op.drop_column('users_challenge_book_of_year', 'review_id')
    op.drop_constraint(None, 'users_book_rating', type_='foreignkey')
    op.drop_constraint(None, 'users_book_rating', type_='unique')
    op.drop_column('users_book_rating', 'review_id')
    op.drop_constraint(None, 'users_book_quotes', type_='foreignkey')
    op.drop_column('users_book_quotes', 'review_id')
    op.drop_constraint(None, 'users_book_notes', type_='foreignkey')
    op.drop_column('users_book_notes', 'review_id')
    op.drop_index(op.f('ix_users_book_review_genres_id'), table_name='users_book_review_genres')
    op.drop_table('users_book_review_genres')
    op.drop_index(op.f('ix_users_book_review_id'), table_name='users_book_review')
    op.drop_table('users_book_review')
    op.drop_index(op.f('ix_books_categories_id'), table_name='books_categories')
    op.drop_table('books_categories')
    # ### end Alembic commands ###
