"""create users_book_notes

Revision ID: 725b1d704ec7
Revises: 17d062ffd73f
Create Date: 2025-11-29 22:46:22.336812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725b1d704ec7'
down_revision: Union[str, Sequence[str], None] = '17d062ffd73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_book_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_book_notes_id'), 'users_book_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_book_notes_id'), table_name='users_book_notes')
    op.drop_table('users_book_notes')
    # ### end Alembic commands ###
