"""create users_challenge_books_alphabet

Revision ID: 7588e4eda91c
Revises: 22a7d740fe08
Create Date: 2025-11-30 19:47:08.556049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7588e4eda91c'
down_revision: Union[str, Sequence[str], None] = '22a7d740fe08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_challenge_books_alphabet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_challenge_books_alphabet_id'), 'users_challenge_books_alphabet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_challenge_books_alphabet_id'), table_name='users_challenge_books_alphabet')
    op.drop_table('users_challenge_books_alphabet')
    # ### end Alembic commands ###
