"""add_colors_to_genres_and_categories

Revision ID: 7fe66b3c43c0
Revises: de8061a41eee
Create Date: 2026-02-02 11:47:58.917023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe66b3c43c0'
down_revision: Union[str, Sequence[str], None] = 'de8061a41eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_categories', sa.Column('color', sa.String(length=7), server_default='#AB66FF', nullable=False))
    op.add_column('genres', sa.Column('color', sa.String(length=7), server_default='#AB66FF', nullable=False))

    op.execute("UPDATE books_categories SET color = '#E0C217' WHERE name = 'Хочу прочитать'")
    op.execute("UPDATE books_categories SET color = '#46AC16' WHERE name = 'Читаю'")
    op.execute("UPDATE books_categories SET color = '#1AB7E3' WHERE name = 'Брошено'")
    op.execute("UPDATE books_categories SET color = '#EE619E' WHERE name = 'Любимые'")
    op.execute("UPDATE books_categories SET color = '#AB66FF' WHERE name = 'Прочитано'")

    op.execute("UPDATE genres SET color = '#FFA2C4' WHERE name = 'Young adult'")
    op.execute("UPDATE genres SET color = '#D4B483' WHERE name = 'Античная литература'")
    op.execute("UPDATE genres SET color = '#069947' WHERE name = 'Белорусская литература'")
    op.execute("UPDATE genres SET color = '#8F4C19' WHERE name = 'Биография, мемуары'")
    op.execute("UPDATE genres SET color = '#0A66C2' WHERE name = 'Бизнес-книги'")
    op.execute("UPDATE genres SET color = '#C62828' WHERE name = 'Боевик'")
    op.execute("UPDATE genres SET color = '#FF8800' WHERE name = 'Детектив'")
    op.execute("UPDATE genres SET color = '#FFDA61' WHERE name = 'Детская литература'")
    op.execute("UPDATE genres SET color = '#416692' WHERE name = 'Журнал, газета, статья'")
    op.execute("UPDATE genres SET color = '#89E835' WHERE name = 'Зарубежная литература'")
    op.execute("UPDATE genres SET color = '#4ABCA1' WHERE name = 'Здоровье, медицина'")
    op.execute("UPDATE genres SET color = '#816E5A' WHERE name = 'Историческая литература'")
    op.execute("UPDATE genres SET color = '#FFB400' WHERE name = 'Комедия'")
    op.execute("UPDATE genres SET color = '#FF9F7C' WHERE name = 'Комикс, манга, манхва, вебтун'")
    op.execute("UPDATE genres SET color = '#B015EF' WHERE name = 'Культура, искусство'")
    op.execute("UPDATE genres SET color = '#7F48CD' WHERE name = 'Мифы, легенды, эпос'")
    op.execute("UPDATE genres SET color = '#008369' WHERE name = 'На иностранном языке'")
    op.execute("UPDATE genres SET color = '#00D9FF' WHERE name = 'Научно-популярная литература'")
    op.execute("UPDATE genres SET color = '#90CBFE' WHERE name = 'Научная фантастика'")
    op.execute("UPDATE genres SET color = '#96B463' WHERE name = 'Нон-фикшн'")
    op.execute("UPDATE genres SET color = '#FF3D00' WHERE name = 'Приключения'")
    op.execute("UPDATE genres SET color = '#7361FF' WHERE name = 'Психология'")
    op.execute("UPDATE genres SET color = '#89EAC8' WHERE name = 'Пьеса'")
    op.execute("UPDATE genres SET color = '#4604A2' WHERE name = 'Религия'")
    op.execute("UPDATE genres SET color = '#FF6565' WHERE name = 'Роман'")
    op.execute("UPDATE genres SET color = '#BEAA12' WHERE name = 'Русская классика'")
    op.execute("UPDATE genres SET color = '#FF2CF1' WHERE name = 'Стихи, поэзия'")
    op.execute("UPDATE genres SET color = '#8E8E8E' WHERE name = 'Техническая литература'")
    op.execute("UPDATE genres SET color = '#222222' WHERE name = 'Триллер'")
    op.execute("UPDATE genres SET color = '#680000' WHERE name = 'Ужасы, мистика'")
    op.execute("UPDATE genres SET color = '#DD96D8' WHERE name = 'Учебная литература'")
    op.execute("UPDATE genres SET color = '#000FB2' WHERE name = 'Фантастика'")
    op.execute("UPDATE genres SET color = '#B68AEB' WHERE name = 'Философия'")
    op.execute("UPDATE genres SET color = '#57B168' WHERE name = 'Фэнтези'")
    op.execute("UPDATE genres SET color = '#145816' WHERE name = 'Энциклопедия, справочник'")
    op.execute("UPDATE genres SET color = '#FF0037' WHERE name = '18+'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'color')
    op.drop_column('books_categories', 'color')
    # ### end Alembic commands ###
