"""add_user_uid

Revision ID: 98c2b40419bb
Revises: aca25c5938ba
Create Date: 2026-03-19 16:19:51.618314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c2b40419bb'
down_revision: Union[str, Sequence[str], None] = 'aca25c5938ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_personal_data', sa.Column('uid', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_users_personal_data_uid'), 'users_personal_data', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_personal_data_uid'), table_name='users_personal_data')
    op.drop_column('users_personal_data', 'uid')
    # ### end Alembic commands ###
