"""create_emotions_tables

Revision ID: aca25c5938ba
Revises: 7fe66b3c43c0
Create Date: 2026-03-07 19:46:44.759869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca25c5938ba'
down_revision: Union[str, Sequence[str], None] = '7fe66b3c43c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_code', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#AB66FF', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_emotions_id'), 'emotions', ['id'], unique=False)
    op.create_table('users_book_review_emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['users_book_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_book_review_emotions_id'), 'users_book_review_emotions', ['id'], unique=False)
    # ### end Alembic commands ###

    emotions_data = [
        ("Азарт", "excitement", "#E0C217"),
        ("Благодарность", "thank", "#BB83F9"),
        ("Вдохновение", "inspiration", "#BB83F9"),
        ("Возмущение", "disturbance", "#FF0004"),
        ("Восторг", "delight", "#E0C217"),
        ("Гнев", "anger", "#FF0004"),
        ("Гордость", "pride", "#BB83F9"),
        ("Грусть", "melancholy", "#006FFF"),
        ("Жалость", "pity", "#006FFF"),
        ("Зависть", "envy", "#FF0004"),
        ("Изумление", "amazement", "#E0C217"),
        ("Интерес", "interest", "#BB83F9"),
        ("Комфорт", "comfort", "#6AD58A"),
        ("Любовь", "love", "#FFA2C4"),
        ("Надежда", "hope", "#BB83F9"),
        ("Напряжение", "voltage", "#FF8832"),
        ("Нежность", "tenderness", "#FFA2C4"),
        ("Ностальгия", "nostalgia", "#006FFF"),
        ("Облегчение", "relief", "#6AD58A"),
        ("Отвращение", "disgust", "#FF8832"),
        ("Печаль", "sadness", "#006FFF"),
        ("Раздражение", "irritation", "#FF0004"),
        ("Размышление", "reflection", "#BB83F9"),
        ("Разочарование", "disappointment", "#8C8C8C"),
        ("Решимость", "determination", "#BB83F9"),
        ("Скука", "boredom", "#8C8C8C"),
        ("Слезы", "tears", "#006FFF"),
        ("Смех", "laughter", "#E0C217"),
        ("Смятение", "confusion", "#006FFF"),
        ("Сопереживание", "empathy", "#006FFF"),
        ("Спокойствие", "calmness", "#6AD58A"),
        ("Страсть", "passion", "#FFA2C4"),
        ("Страх", "fear", "#FF8832"),
        ("Стыд", "shame", "#FF0004"),
        ("Тревога", "anxiety", "#FF8832"),
        ("Предвкушение", "anticipation", "#FFA2C4"),
        ("Ужас", "horror", "#FF8832"),
        ("Уныние", "despondency", "#8C8C8C"),
        ("Шок", "shock", "#E0C217"),
        ("Эйфория", "euphoria", "#E0C217"),
        ("Ярость", "rage", "#FF0004"),
    ]

    for name, img_code, color in emotions_data:
        op.execute(
            sa.text(
                "INSERT INTO emotions (name, image_code, color) VALUES (:name, :img, :color) ON CONFLICT (name) DO NOTHING")
            .bindparams(name=name, img=img_code, color=color)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_book_review_emotions_id'), table_name='users_book_review_emotions')
    op.drop_table('users_book_review_emotions')
    op.drop_index(op.f('ix_emotions_id'), table_name='emotions')
    op.drop_table('emotions')
    # ### end Alembic commands ###
