"""create users_challenge_book_of_year

Revision ID: bb018fe2ae50
Revises: 7588e4eda91c
Create Date: 2025-11-30 19:56:55.401962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb018fe2ae50'
down_revision: Union[str, Sequence[str], None] = '7588e4eda91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_challenge_book_of_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_challenge_book_of_year_id'), 'users_challenge_book_of_year', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_challenge_book_of_year_id'), table_name='users_challenge_book_of_year')
    op.drop_table('users_challenge_book_of_year')
    # ### end Alembic commands ###
