"""create users_book_rating

Revision ID: bd8b55d6e45d
Revises: 758366379bad
Create Date: 2025-11-29 23:41:46.150237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8b55d6e45d'
down_revision: Union[str, Sequence[str], None] = '758366379bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_book_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_rating', sa.Integer(), nullable=False),
    sa.Column('characters_rating', sa.Integer(), nullable=True),
    sa.Column('plot_rating', sa.Integer(), nullable=True),
    sa.Column('relations_rating', sa.Integer(), nullable=True),
    sa.Column('emotionality_rating', sa.Integer(), nullable=True),
    sa.Column('ending_rating', sa.Integer(), nullable=True),
    sa.Column('easy_reading_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_book_rating_id'), 'users_book_rating', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_book_rating_id'), table_name='users_book_rating')
    op.drop_table('users_book_rating')
    # ### end Alembic commands ###
