"""create users_statistics

Revision ID: da48215a7e8f
Revises: ddfa1f232766
Create Date: 2025-11-30 20:20:49.550020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da48215a7e8f'
down_revision: Union[str, Sequence[str], None] = 'ddfa1f232766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('books_in_library', sa.Integer(), nullable=True),
    sa.Column('books_read', sa.Integer(), nullable=True),
    sa.Column('books_favorites', sa.Integer(), nullable=True),
    sa.Column('favorite_author', sa.String(length=255), nullable=True),
    sa.Column('favorite_genre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_statistics_id'), 'users_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_statistics_id'), table_name='users_statistics')
    op.drop_table('users_statistics')
    # ### end Alembic commands ###
