"""add FK from challenges to alphabet and book_of_year

Revision ID: ddfa1f232766
Revises: e44138ccdf6a
Create Date: 2025-11-30 20:08:41.767755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfa1f232766'
down_revision: Union[str, Sequence[str], None] = 'e44138ccdf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_challenge_book_of_year', sa.Column('challenge_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenge_book_of_year', 'users_challenges', ['challenge_id'], ['id'])
    op.add_column('users_challenge_books_alphabet', sa.Column('challenge_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_challenge_books_alphabet', 'users_challenges', ['challenge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_challenge_books_alphabet', type_='foreignkey')
    op.drop_column('users_challenge_books_alphabet', 'challenge_id')
    op.drop_constraint(None, 'users_challenge_book_of_year', type_='foreignkey')
    op.drop_column('users_challenge_book_of_year', 'challenge_id')
    # ### end Alembic commands ###
