"""add verification fields

Revision ID: de8061a41eee
Revises: 33202f8c22ce
Create Date: 2025-12-15 01:17:33.290890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8061a41eee'
down_revision: Union[str, Sequence[str], None] = '33202f8c22ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_personal_data', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users_personal_data', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_personal_data', 'is_verified')
    op.drop_column('users_personal_data', 'verification_code')
    # ### end Alembic commands ###
