"""create users_book_quotes

Revision ID: ecb9ff41ebcb
Revises: 725b1d704ec7
Create Date: 2025-11-29 23:10:13.421630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb9ff41ebcb'
down_revision: Union[str, Sequence[str], None] = '725b1d704ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_book_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('quote_author', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_book_quotes_id'), 'users_book_quotes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_book_quotes_id'), table_name='users_book_quotes')
    op.drop_table('users_book_quotes')
    # ### end Alembic commands ###
