"""create literature_works and books_editions

Revision ID: f67d12b7990d
Revises: 316574416a9d
Create Date: 2025-11-29 21:45:44.102699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67d12b7990d'
down_revision: Union[str, Sequence[str], None] = '316574416a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literature_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_literature_works_id'), 'literature_works', ['id'], unique=False)
    op.create_table('books_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literature_work_id', sa.Integer(), nullable=False),
    sa.Column('original_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['literature_work_id'], ['literature_works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_books_editions_id'), 'books_editions', ['id'], unique=False)
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_index(op.f('ix_books_editions_id'), table_name='books_editions')
    op.drop_table('books_editions')
    op.drop_index(op.f('ix_literature_works_id'), table_name='literature_works')
    op.drop_table('literature_works')
    # ### end Alembic commands ###
